name: Deploy BMS to Server

on:
  push:
    branches: [ main, production ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Create uploads directory
      run: mkdir -p uploads
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          cd /var/www/bms-app
          git pull origin main
          npm ci --production
          npm run build
          pm2 restart bms-app || pm2 start ecosystem.config.js
          pm2 save
    
    - name: Health check
      run: |
        sleep 10
        curl -f http://${{ secrets.SERVER_HOST }}/health || exit 1