# Updated GitHub Actions workflow to fix JSON API response issue
# Replace your existing workflow with this configuration

name: BidFlowAI Pipeline

on:
  push:
    branches:
      - production
env:
  KEY_NAME: "BidFlowAI" 
  FILE_PATH: "BidFlowAI" 

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"
 
      - name: Install Dependencies
        run: |
          npm install
 
      - name: Build Project
        run: |
          npm run build
          
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy with Simple Production Server
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/html/${{ env.FILE_PATH }}
            
            # Stop all processes first
            pm2 delete all || true
            pkill -f node || true
            
            # Git operations
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/${{ env.KEY_NAME }}  
            git config --global --add safe.directory /var/www/html/${{ env.FILE_PATH }}
            git fetch --all
            git reset --hard origin/production
            
            # Clean install
            rm -rf package-lock.json node_modules dist
            
            # Environment setup
            export NODE_ENV=production
            export PORT=3000
            
            # Install and build
            npm install
            npm run build
            
            # Verify build
            if [ ! -d "dist/public" ] || [ ! -f "dist/public/index.html" ]; then
              echo "Build failed - missing dist/public files"
              exit 1
            fi
            
            # Start with simple production server
            pm2 start server/simple-production.js --name BidFlowAI --env production
            pm2 save
            
            # Run comprehensive health checks
            sleep 5
            echo "Running deployment verification..."
            node server/health-check.js

  notify-teams:
    runs-on: ubuntu-latest
    needs: 
      - build
      - deploy
    if: always() 
    steps:
      - name: Set Color and Message for Success
        if: ${{ needs.build.result == 'success' && needs.deploy.result == 'success' }}
        run: |
          echo "COLOR=success" >> $GITHUB_ENV
          echo "MESSAGE=✅ BidFlowAI deployed successfully! Simple production server active with working authentication." >> $GITHUB_ENV

      - name: Set Color and Message for Failure
        if: ${{ needs.build.result != 'success' || needs.deploy.result != 'success' }}
        run: |
          echo "COLOR=failure" >> $GITHUB_ENV
          echo "MESSAGE=❌ BidFlowAI deployment failed!" >> $GITHUB_ENV

      - name: Send Notification to Teams
        uses: mikesprague/teams-incoming-webhook-action@v1.13.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          title: "BidFlowAI Deployment Status"
          message: ${{ env.MESSAGE }}
          deploy-card: true
          color: ${{ env.COLOR }}